### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by xypron** [dextero/tm-projekt#2]
@MichalPawlicki  @dextero 

I would like to reuse some of the code but unfortunately your project does not have any license information attached.

Best regards

Heinrich

**Comment by dextero** [comment]
Hi,

I added a license to the project (MIT). May I ask what do you intend to use the code for?

Please be aware that the whole project was created as an university assignment, and was not touched at all since over 5 years. It is very likely it has a number of bugs. I would suggest using some other, better supported TCP stack (e.g. [LwIP](https://savannah.nongnu.org/projects/lwip/)).

Best regards,
Marcin

**Comment by xypron** [comment]
Thanks for adding a license.

I want to write a program logging LoRaWAN packets and your raw socket seemed well suited.

Best regards

Heinrich
